### ISSUE TITLE
output path for model-related files

### ISSUE THREAD

**Issue by tarakc02** [ppact/extraction#28]
fast.ai sets a default path for model outputs (including e.g. the language model encoder and other model components). By default, this is in the `models` directory, but we should keep to our convention of putting all generated artifacts in `output`. I believe the way to change this is to set the `path` argument for [TextDataLoaders.from_df](https://docs.fast.ai/text.data.html#TextDataLoaders.from_df), although it's worth checking to make sure.

**Comment by ayyubibrahimi** [comment]
Done. Closing this.
