### ISSUE TITLE
Store text as .TXT files rather than as a string in a CSV table

### ISSUE THREAD

**Issue by rajivsinclair** [ppact/extraction#9]
Do you think it might be better to store the full OCR text contents as a txt file on Dropbox (matched to each PDF on Dropbox) instead of as a very long string in a CSV/table on WRGL?

This is just a question/thought I had so that we can avoid the potential for issues that stem for commas. What do you think @tarakc02?

**Comment by tarakc02** [comment]
I like that idea. We can use the same naming convention as with the pdfs, so each text file is `<docid>.txt`. In this case, the documents table would include columns for dropbox path/id/hash for both the pdf and the textfile, right?

**Comment by rajivsinclair** [comment]
Great! 

Yes, re: file identifiers, that is what I had in mind too.

**Comment by rajivsinclair** [comment]
@tarakc02 could you bump this up in priority **above** the _.doc → .pdf conversion_ task?

**Comment by tarakc02** [comment]
ok, latest update includes links to both pdf and text files on dropbox. Note for downstream processes that consume this table that the file paths are now `pdf_db_path` and `txt_db_path`, whereas previously we only had a column called `file_db_path` (which no longer exists)

**Comment by rajivsinclair** [comment]
Thanks! @tarakc02 can you confirm that the `hrg_text` field is now redundant? will the `txt` files contain the same text as the `hrg_text` field?

**Comment by tarakc02** [comment]
the `hrg_text` field includes just the text extracted from hearings, whereas the `txt` files include the full text of each  document. some documents just consist of single hearings, in which case the two will be identical, but most are meetings that include various other items of business as well as one or more hearings, and in those cases the `hrg_text` is much shorter and more specific.

**Comment by rajivsinclair** [comment]
Got it. Thanks for clarifying!
